### ISSUE TITLE
Non implemented IPublishedContent methods should throw

### ISSUE THREAD

**Issue by mortenbock** [leekelleher/umbraco-doc-type-grid-editor#1]
Given that the embedded content will be represented using the IPublishedContent interface, without actually being a node, I think that any properties/methods that do not make sense to use for a piece of embedded content should throw a NotSupportedException or similar, with a message like "Embedded content does not have an Id".

This will make sure that if anyone uses their own extension methods or similar on that kind of object, then it will throw if something is not actually supported, and not return a default value that might not make sense, and might make it hard to debug why things are not working.

**Comment by mattbrailsford** [comment]
Ok, I have been thinking about this. Right now, we do return default values, rather than throw exceptions, which to be honest, I think it valid. I think we could make it a little better though by having something inherit from the parent node (ie, create date etc should be exactly the same as the parent node as it will be created / published at the same time). 

I think that the only one that vaguely causes confusion is ID, which we do currently return 0. Now I'll have to check this, but I'm not sure if throwing an exception might cause a problem as I believe some of the Umbraco.Field internal stuff will check the node id, so if it throws an exception, it would break rendering (ok if you are specifically accessing ID, but if Umbraco.Field checks the field internally every time, we need a way to have it continue without failing).

If that is the case, returning an int might have to stay. The only thing I could suggest to do otherwise, is maybe return a specific non 0 number so that you could identify it as being nested content (ie, -100 or something).

I dunno, what do you think? in terms of the ID field aswell as inhering the other fields?

**Comment by mortenbock** [comment]
I think it does make sense to inherit some of the properties from the containing node. It might even be fair to return the container as the parent.

With regards to Umbraco.Field, would you even be able to use that anyway? Won't that always go to to UmbracoContext's current node, which will never be an embedded node?

If in any way possible, I would prefer the ID,Level and Version properties to throw, since they do not make sense for embedded content, and will cause problems if used to try and get stuff from for example the Db or examine. If you a worried that people might get stuck on those exceptions, maybe add a config option to return defaults instead, and add the config info to the exception message so people can turn it off if it causes problems, and they don't mind getting a fictional value form those props.

That way the dev is informed about what he is doing, why it does not work, and will not get stuck since he can change the behaviour.

**Comment by mattbrailsford** [comment]
Umbraco.Field does work, most of the time :) There are some items that do go to the context (the special "pageName" keyword for example), but most calls do work use the passed in node (why it doesn't just use the passed in node, rather than re-fetching it from the content cache sometimes, I don't know, but that's a core thing).

Regarding Level, wouldn't it be fine to return either the parent level? or the parent level + 1 (I could see why that would be confusing though), and again, for version, that could use the parent version number right? (it's part of the parent node so must share the version number).

**Comment by mortenbock** [comment]
I guess Level is a matter of preference. It's not in the tree, so it doesn't have a level. In my opinion.

With regard to the version, if you inherit from parent, then imagine this:

I get an IPublishedContent which is in fact embedded, but I don't know that (because I'm a framework extension method). I ask for the version number, and then fetch that version from the database. But wait, that is not the same piece of content that I had before. It's a different document. But I had a Guid. That is unique, right? :)

**Comment by leekelleher** [comment]
Interesting looking at how Articulate handles it's own objects inherited from `PublishedContentWrapped`.

See how the `Id` is returned: [ArticulateVirtualPage.cs#L49](https://github.com/Shazwazza/Articulate/blob/master/Articulate/Models/ArticulateVirtualPage.cs#L49). Same goes for `Path` and `Level`

**Comment by mortenbock** [comment]
@leekelleher That is one way to go about it. But I still question the reasoning for it. You might be able to get an ID, but you can't use the Id for anything, since it will not work with any of the library methods that accept an id?

Basically it's an Id for the sake of an Id? Maybe event confusing the user as to where this Id comes from?

**Comment by mattbrailsford** [comment]
Interesting...

I wondered about trying to create sudo unique IDs based on primes of the current node ID, but don't know how stupid that would be :) I think though, using 0 shouldn't be an issue, as it won't result in a node being resolved if people try to fetch it, and we don't really have a way of providing the cells with their own ID so anything else is going to be pointless.

On a side note Lee, would could look at populating IDs in NC purely within the context of a given list (see bobs forum post) but again, we should discuss that one elsewhere (so hard when there is much crossover)

**Comment by leekelleher** [comment]
@mortenbock Yup, you're correct - it's an `Id` value just for the sake of it - it can't be used elsewhere.

I'm not sure what the resolution is at this point either.

**Comment by mattbrailsford** [comment]
I think this maybe be one of those things that we have to see what people say. If we see people hitting the same problems all the time, we can see it's an issue and look at a fix, but right now, there are two options which seem equally viable.

In my opinion, I think leaving the ID at 0 should be fine. People will be implementing partials knowing that they are grid editor partials and so know the node doesn't really exist. If you were able to access the node by any other means than via our API (ie, through the Umbraco API pretending to be a true node) I might consider making it more "obvious".

I still think populating some of the other properties based on the containing content node is a good idea though so where we can, I think we should try to give meaningful values.

**Comment by mattbrailsford** [comment]
Should we close this issue down, and open up a new one to populate meaningful properties?

**Comment by leekelleher** [comment]
:+1:
