### ISSUE TITLE
Preview of unpublished content

### ISSUE THREAD

**Issue by dsbahr** [leekelleher/umbraco-doc-type-grid-editor#18]
Hi. 

Is it i possible to preview the content of the grid on a node that is unpublished? 

When I'm choosing an unpublished node in the Umbraco Backoffice, that contains the DocType grid, then  I get an error looking like this: 

![image](https://cloud.githubusercontent.com/assets/1941037/8105159/f025080a-1036-11e5-86bc-970eb395854d.png)

Is it possible to enable preview of the content even though its unpublished instead of the error?

Great work btw!

Thanks, 

/David

**Comment by leekelleher** [comment]
Hi @dsbahr, thanks for raising this - we'll look into it.

(We've only just got back from CodeGarden 15, hence the delay in replying)

**Comment by BluefinDigital** [comment]
+1,  just handling the 404's would be a good improvement

**Comment by mattbrailsford** [comment]
Need to decide what to do here. I can make this work to some extent because in preview mode we pass a dummy node to populate the data with, so it has access to all the data in the DTGE value field. The only thing that wouldn't work is if that grid editor needed any outside context (ie, some value from the master node / the master nodes hierarchy) as this wouldn't be published / accessible.

Thoughts?

**Comment by mattbrailsford** [comment]
Ok, I've added a fix that works to a degree. 

Basically the way the previewer works is to request "/nodeid" then a globally registered attribute hijacks the request to use the previewer .cshtml file as the view. The reason for using /nodeid is that the request is then run in the context of the page the DTGE is sat on, so that if the editor needs some context from the page (ie, maybe the grid needs to know the current nodes URL etc) then it knows it can just access the current page property in the view model.

The problem is, when the page is unpublished /nodeid throws a 404, hence the error. 

The fix I've applied then is to continue to use /nodeid, but if editorState.current says there is no publishDate (ie, there is no published version of the node available), then instead it will call /?nodeId=123. This does mean that the request will run in the context of the root node, rather than the node being edited, but it at least gives you the ability to run previews, and if you really need context, you can use the nodeId param to lookup the node from the ContentService. 

Given this is only needed for previews though, where I would suggest to display a simplified version of whatever your DTGE is for, I'd generally suggest to make sure these aren't context sensitive anyway, but if you absoluty must, then at least there is a way.

**Comment by davebeesley** [comment]
Hey @mattbrailsford.
Has this fix been applied in 0.2.0?
I am seeing this issue on my installation where pages don't have a template applied to them.

**Comment by mattbrailsford** [comment]
Is your homepage published?

**Comment by davebeesley** [comment]
Yeah
