### ISSUE TITLE
Default Surface Controller

### ISSUE THREAD

**Issue by revolution42** [leekelleher/umbraco-doc-type-grid-editor#36]
It would be great to have a default surface controller for all grid elements or specify the controller to use in the grid setup

I currently use strongly typed views using ditto and have to create a separate surface controller for each type although they inherit from a base type.

**Comment by mattbrailsford** [comment]
Fixed in commit 00ed7f9. A DefaultDocTypeGridEditorSurfaceControllerResolver has been added (works the same way as the umbraco [DefaultRenderMvcControllerResolver](https://our.umbraco.org/documentation/reference/routing/custom-controllers)) on which you can register a default DocTypeGridEditorSurfaceController to use for all requests. It will try looking for a more specific controller first, but if one isn't found, and a default is set, it will look for an appropriately named action on the default controller, and if one can't be found, defaults to "Index". 

It's important to note, If you set a DefaultDocTypeGridEditorSurfaceController, then the Html helper will ALWAYS use that controller for every call to it.

**Comment by revolution42** [comment]
Just implementing this now into my solution and seem to have a problem with the order that my IApplicationEventHandler is loaded and the doctypegrideditor is loaded.

This happens about 50% of the time, 
```
Current has not been initialized on Our.Umbraco.DocTypeGridEditor.Web.Mvc.DefaultDocTypeGridEditorSurfaceControllerResolver. You must initialize Current before trying to read it.
```

**Comment by mattbrailsford** [comment]
That's weird, IApplicationEventHandler should always occur first. Do you get that error on the front end when you try to view the page? or is it some place else?

**Comment by revolution42** [comment]
The problem is that there is 2 IApplicationEventHandler one for the doc type editor and one for my application where I register the resolver.

It appears to change how each one is loaded.

**Comment by mattbrailsford** [comment]
Ahh, ok, I get the issue now.

**Comment by revolution42** [comment]
My hacky fix is to add this to both ApplicationStarting.

Apart from that works a treat I have it in about 15 doctypes

```
if(!DefaultDocTypeGridEditorSurfaceControllerResolver.HasCurrent)
{
    DefaultDocTypeGridEditorSurfaceControllerResolver.Current = new DefaultDocTypeGridEditorSurfaceControllerResolver();
}
```
